name: Lint

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx awesome-lint

  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for dead links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --config lychee.toml README.md
          fail: true
